[package]
name = "utils-rs"
version = "0.1.10"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.23", optional = true, default-features = false, features = ["std"] }
futures = { version = "0.3.26", optional = true, default-features = false, features = ["std"] }
lazy_static = { version = "1.4.0", optional = true, default-features = false }
log = { version = "0.4.17", optional = true, default-features = false, features = ["std"] }
rolling-file = { version = "0.2.0", optional = true, default-features = false }
rust_decimal = { version = "1.28.0", optional = true, default-features = false }
serde = { version = "1.0.152", optional = true, default-features = false, features = ["derive", "std"] }
serde_yaml = { version = "0.9.17", optional = true, default-features = false }
sqlx = { version = "0.6.2", optional = true, default-features = false, features = ["macros", "runtime-tokio-rustls", "mysql", "chrono", "decimal"] }
thiserror = { version = "1.0.38", optional = true, default-features = false }
time = { version = "0.3.17", optional = true, default-features = false, features = ["macros", "std"] }
tokio = { version = "1.25.0", optional = true, default-features = false, features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1.37", optional = true, default-features = false, features = ["std"] }
tracing-appender = { version = "0.2.2", optional = true, default-features = false }
tracing-error = { version = "0.2.0", optional = true, default-features = false }
# tracing-subscriber = { version = "0.3.11", default-features = false, features = ["tracing-log", "ansi", "local-time"] }
tracing-subscriber = { version = "0.3.16", optional = true, default-features = false, features = ["tracing-log", "ansi", "time", "std"] }
uuid = { version = "1.3.0", optional = true, default-features = false, features = ["v4", "fast-rng", "std"] }

[features]
default = ["all"]
all = ["cell", "mysqlx_batch", "qh", "sizehmap", "timer", "ulog"]
cell = []
mysqlx = ["yaml", "lazy_static", "log", "serde", "sqlx", "thiserror", "tokio", "uuid"]
mysqlx_batch = ["mysqlx"]
qh = ["mysqlx_batch", "ymdhms", "futures", "lazy_static", "rust_decimal", "thiserror", "tokio", "tracing"]
sizehmap = []
timer = ["futures", "tokio"]
ulog = ["rolling-file", "time", "tracing", "tracing-appender", "tracing-error", "tracing-subscriber"]
yaml = ["serde", "serde_yaml", "thiserror", "tracing"]
ymdhms = ["chrono"]
