database = ["tmp1", "tmp2", "gp_swindex"]
[[table]]
tbl-database = "gp-swindex"
tbl-name = "tbl-tmp-1"
tbl-private-key = ["person-id"]
tbl-index = ["person-id-2"]
person-id = { type = "VARCHAR(60)", not-null = true, default = "", comment = "1" }
person-id-2 = { type = "VARCHAR(60)", not-null = true, default = "", comment = "2" }
person-id-3 = { type = "VARCHAR(60)", not-null = true, comment = "3" }
brithday = { type = "int(8)", not-null = true, default = "0", comment = "生日" }
create-time = { type = "DATETIME(6)", not-null = true, default = "CURRENT_TIMESTAMP(6)", comment = "更新时间" }
update-time = { type = "DATETIME(6)", not-null = true, default = "CURRENT_TIMESTAMP(6)", on-update = "CURRENT_TIMESTAMP(6)", comment = "更新时间" }
ttt = { type = "VARCHAR(60) NOT NULL DEFAULT '0' ON UPDATE CURRENT_TIMESTAMP(6) COMMENT=''" }

[[table]]
tbl-database = "gp-swindex"
tbl-name = "tbl-tmp-2"
tbl-private-key = ["person-id"]
tbl-index = ["person-id-2"]
person-id = { type = "VARCHAR(60)", not-null = true, default = "", comment = "1" }
person-id-2 = { type = "VARCHAR(60)", not-null = true, default = "", comment = "2" }
person-id-3 = { type = "VARCHAR(60)", not-null = true, comment = "3" }
brithday = { type = "int(8)", not-null = true, default = "0", comment = "生日" }
create-time = { type = "DATETIME(6)", not-null = true, default = "CURRENT_TIMESTAMP(6)", comment = "更新时间" }
update-time = { type = "DATETIME(6)", not-null = true, default = "CURRENT_TIMESTAMP(6)", on-update = "CURRENT_TIMESTAMP(6)", comment = "更新时间" }
